parliament:
  name: House of AI
  members:
  - name: Mock-A
    provider: ollama
    model: gemma2
  - name: Mistral
    provider: ollama
    model: mistral
  - name: Gemma
    provider: ollama
    model: gemma2
providers:
  ollama:
    base_url: http://localhost:11434/v1
